name: ratchet
on:
  workflow_dispatch: # Enable manual trigger to run workflow.
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # “At minute 15 past hour 5 and 17 on every day-of-week from Monday through Friday.”
    - cron: "15 5,17 * * 1-5"
jobs:
  ratchet:
    name: "ratchet"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        workflow: ["ratchet.yml", "terraform.yml", "tfsec.yml", "trivy-workflow.yml", "trivy.yml"]
    steps:
      # ------------------------------------------------------------------------
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # ratchet:actions/checkout@v3
      # ------------------------------------------------------------------------
      # ------------------------------------------------------------------------
      - name: Setup Ratchet
        run: |
          SCRIPT_DIRECTORY=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

          # https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html
          shopt -s inherit_errexit # If set, command substitution inherits the value of the errexit option, instead of unsetting it in the subshell environment. This option is enabled when POSIX mode is enabled.

          # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
          set -o errexit  #Same as -e.
          set -o errtrace # Same as -E.
          set -o nounset  # Same as -u.
          set -o xtrace   # Same as -x.
          set -o pipefail # If set, the return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. This option is disabled by default.
          # set -eEuxo pipefail

          mkdir --parents --verbose ${SCRIPT_DIRECTORY}/ratchet_files \
              && cd $_

          declare -a urlArray=(
              'https://github.com/sethvargo/ratchet/releases/download/v0.3.1/ratchet_0.3.1_linux_amd64.tar.gz'
              'https://github.com/sethvargo/ratchet/releases/download/v0.3.1/ratchet_0.3.1_SHA512SUMS'
              'https://github.com/sethvargo/ratchet/releases/download/v0.3.1/ratchet_0.3.1_SHA512SUMS.sig'
              'https://github.com/sethvargo.gpg'
          )

          for url in ${urlArray[@]}; do
              curl \
                  --fail \
                  --location \
                  --remote-name \
                  --remote-name-all \
                  --remote-time \
                  --request GET \
                  --show-error \
                  --silent \
                  "${url}"
          done

          sha512sum --check ratchet_0.3.1_SHA512SUMS 2>&1 | grep --quiet OK # https://stackoverflow.com/questions/23228209/piping-shasum-to-grep-but-grep-returning-all-lines-of-piped-input-even-ones-th/23228588#23228588

          # gpg --batch --delete-key --yes 0xDA181DFE1B26293F42BBEC139C01CC8AB5D3F179
          gpg --keyid-format long --keyserver hkp://keyserver.ubuntu.com --recv-keys 0xDA181DFE1B26293F42BBEC139C01CC8AB5D3F179
          gpg --keyid-format long --list-keys --with-fingerprint 0xDA181DFE1B26293F42BBEC139C01CC8AB5D3F179

          gpg --keyid-format long --verify ratchet_0.3.1_SHA512SUMS.sig ratchet_0.3.1_SHA512SUMS 2>&1 | grep 'Good signature'

          tar -xzvf ratchet_0.3.1_linux_amd64.tar.gz ratchet

          # sha512sum --check $(grep ratchet_0.3.1_linux_amd64.tar.gz ratchet_0.3.1_SHA512SUMS) ratchet_0.3.1_linux_amd64.tar.gz

          shasum -a 512 -c ratchet_0.3.1_SHA512SUMS | grep --quiet OK

          cd --verbose ${SCRIPT_DIRECTORY}
    # ------------------------------------------------------------------------
