# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: tfsec
on:
  workflow_dispatch: # Enable manual trigger to run workflow.
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # “At minute 30 past hour 5 and 17 on every day-of-week from Monday through Friday.”
    - cron: '30 5,17 * * 1-5'
jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # ratchet:actions/checkout@v3
      - uses: aquasecurity/tfsec-action@141b4983d1a2ada087fa804bc40e59e9cc138bcf # ratchet:aquasecurity/tfsec-action@v1.0.2
        # https://github.com/aquasecurity/tfsec-action
      - uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 # ratchet:aquasecurity/tfsec-sarif-action@v0.1.4
        # https://github.com/aquasecurity/tfsec-sarif-action
        with:
          sarif_file: tfsec.sarif
          full_repo_scan: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@b2a92eb56d8cb930006a1c6ed86b0782dd8a4297 # ratchet:github/codeql-action/upload-sarif@v2.1.35
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
